/* Generated By:JJTree: Do not edit this line. ASTConstantExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTConstantExpression extends SimpleNode {
  public ASTConstantExpression(int id) {
    super(id);
  }

  public ASTConstantExpression(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3f101f07db63ab0ff4b529ab1d45dacc (do not edit this line) */
