/* Generated By:JJTree: Do not edit this line. ASTDirectDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDirectDeclarator extends SimpleNode {
  public ASTDirectDeclarator(int id) {
    super(id);
  }

  public ASTDirectDeclarator(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=291e45d124f60d806e5b12babd8b60ba (do not edit this line) */
