/* Generated By:JJTree: Do not edit this line. ASTDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDeclarator extends SimpleNode {
  public ASTDeclarator(int id) {
    super(id);
  }

  public ASTDeclarator(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=594a6ee9e9fa8a5cc8c958215a66a5f6 (do not edit this line) */
