/* Generated By:JJTree: Do not edit this line. ASTEnumSpecifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEnumSpecifier extends SimpleNode {
  public ASTEnumSpecifier(int id) {
    super(id);
  }

  public ASTEnumSpecifier(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0ebc4fe4ef610a8444c456b1d324bc38 (do not edit this line) */
