/* Generated By:JJTree: Do not edit this line. ASTExpressionStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpressionStatement extends SimpleNode {
  public ASTExpressionStatement(int id) {
    super(id);
  }

  public ASTExpressionStatement(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=80f0a6cb52c2e34f3baf9e347c652b18 (do not edit this line) */
