/* Generated By:JJTree: Do not edit this line. ASTExternalDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExternalDeclaration extends SimpleNode {
  public ASTExternalDeclaration(int id) {
    super(id);
  }

  public ASTExternalDeclaration(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5313b37f7a3c3b832f3f93a85879e1e3 (do not edit this line) */
