/* Generated By:JJTree: Do not edit this line. ASTEnumeratorList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEnumeratorList extends SimpleNode {
  public ASTEnumeratorList(int id) {
    super(id);
  }

  public ASTEnumeratorList(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fec1fb7b04b3030db9e78ebfe519a233 (do not edit this line) */
