/* Generated By:JJTree: Do not edit this line. ASTInitializer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInitializer extends SimpleNode {
  public ASTInitializer(int id) {
    super(id);
  }

  public ASTInitializer(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=93ef43b79fdbbadec4d0dca73d5c1642 (do not edit this line) */
