/* Generated By:JJTree: Do not edit this line. ASTParameterTypeList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTParameterTypeList extends SimpleNode {
  public ASTParameterTypeList(int id) {
    super(id);
  }

  public ASTParameterTypeList(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cdd9365709d44a985c14406046fb5e5a (do not edit this line) */
