/* Generated By:JJTree: Do not edit this line. ASTParameterList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTParameterList extends SimpleNode {
  public ASTParameterList(int id) {
    super(id);
  }

  public ASTParameterList(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cd2a2ff3a6e5b422f65abc63d321520d (do not edit this line) */
