/* Generated By:JJTree: Do not edit this line. ASTStorageClassSpecifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStorageClassSpecifier extends SimpleNode {
  public ASTStorageClassSpecifier(int id) {
    super(id);
  }

  public ASTStorageClassSpecifier(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4367d6c51523edaa965bdfb65324459c (do not edit this line) */
