/* Generated By:JJTree: Do not edit this line. ASTSelectionStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSelectionStatement extends SimpleNode {
  public ASTSelectionStatement(int id) {
    super(id);
  }

  public ASTSelectionStatement(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e460f8ea2a5bea3e665d4b7e232bb346 (do not edit this line) */
