/* Generated By:JJTree: Do not edit this line. ASTStructDeclaratorList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStructDeclaratorList extends SimpleNode {
  public ASTStructDeclaratorList(int id) {
    super(id);
  }

  public ASTStructDeclaratorList(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0f79db7c32befc9b6b7b6ae6b0047c26 (do not edit this line) */
