/* Generated By:JJTree: Do not edit this line. ASTStructDeclarationList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStructDeclarationList extends SimpleNode {
  public ASTStructDeclarationList(int id) {
    super(id);
  }

  public ASTStructDeclarationList(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5f5de94c34c6196f5325d95ab66ad442 (do not edit this line) */
