/* Generated By:JJTree: Do not edit this line. ASTStructDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStructDeclarator extends SimpleNode {
  public ASTStructDeclarator(int id) {
    super(id);
  }

  public ASTStructDeclarator(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=75e3defb614df5f65fc0e9e9996754f9 (do not edit this line) */
