/* Generated By:JJTree: Do not edit this line. ASTSpecifierQualifierList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSpecifierQualifierList extends SimpleNode {
  public ASTSpecifierQualifierList(int id) {
    super(id);
  }

  public ASTSpecifierQualifierList(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cbc90b95207d1c599768f551c9d63a46 (do not edit this line) */
