/* Generated By:JJTree: Do not edit this line. ASTStructOrUnionSpecifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStructOrUnionSpecifier extends SimpleNode {
  public ASTStructOrUnionSpecifier(int id) {
    super(id);
  }

  public ASTStructOrUnionSpecifier(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4e8a10764eaa5d2be2e3fc9ebc762597 (do not edit this line) */
