/* Generated By:JJTree: Do not edit this line. ASTTypedefName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTypedefName extends SimpleNode {
  public ASTTypedefName(int id) {
    super(id);
  }

  public ASTTypedefName(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e6bfd17d4f972c1a7c23fe5ce6340d8e (do not edit this line) */
