/* Generated By:JJTree: Do not edit this line. ASTTypeSpecifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTypeSpecifier extends SimpleNode {
  public ASTTypeSpecifier(int id) {
    super(id);
  }

  public ASTTypeSpecifier(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b6ca85d984562d828967a5ae0f5cae41 (do not edit this line) */
