/* Generated By:JJTree: Do not edit this line. ASTUnaryOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTUnaryOperator extends SimpleNode {
  public ASTUnaryOperator(int id) {
    super(id);
  }

  public ASTUnaryOperator(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=87e8f7cf931fa33a43cc380b783590a7 (do not edit this line) */
