package gui;

import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

import gui.Logs.enumLogType;

/**
 * Parameters Interface : Ask user to fill the application parameters. Class
 * generate from Netbeans Form Designer.
 * 
 * @author pev
 */
public class Params extends javax.swing.JFrame {

	// ==============================================================
	// CONSTRUCTOR
	// ==============================================================

	/**
	 * Serialization
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form UI_Params
	 */
	public Params() {
		initComponents();
	}

	// ==============================================================
	// COMPONENTS
	// ==============================================================

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		panelMain = new javax.swing.JPanel();
		panelHeader = new javax.swing.JPanel();
		labelHeader = new javax.swing.JLabel();
		panelBottom = new javax.swing.JPanel();
		btnExecute = new javax.swing.JButton();
		panelContent = new javax.swing.JPanel();
		panelContentLeft = new javax.swing.JPanel();
		labelInput = new javax.swing.JLabel();
		textInput = new javax.swing.JTextField();
		labelOutput = new javax.swing.JLabel();
		textOutput = new javax.swing.JTextField();
		panelContentRight = new javax.swing.JPanel();
		btnInput = new javax.swing.JButton();
		btnOuput = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		panelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		labelHeader.setText("Parameters");

		javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
		panelHeader.setLayout(panelHeaderLayout);
		panelHeaderLayout
				.setHorizontalGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								panelHeaderLayout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(labelHeader).addGap(147, 147, 147)));
		panelHeaderLayout
				.setVerticalGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(panelHeaderLayout.createSequentialGroup().addContainerGap().addComponent(labelHeader)
								.addContainerGap(15, Short.MAX_VALUE)));

		btnExecute.setText("Execute");
		btnExecute.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnExecuteActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout panelBottomLayout = new javax.swing.GroupLayout(panelBottom);
		panelBottom.setLayout(panelBottomLayout);
		panelBottomLayout
				.setHorizontalGroup(panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								panelBottomLayout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(btnExecute).addGap(135, 135, 135)));
		panelBottomLayout
				.setVerticalGroup(panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBottomLayout.createSequentialGroup()
								.addContainerGap(10, Short.MAX_VALUE).addComponent(btnExecute).addContainerGap()));

		labelInput.setText("Input :");

		labelOutput.setText("Output :");

		javax.swing.GroupLayout panelContentLeftLayout = new javax.swing.GroupLayout(panelContentLeft);
		panelContentLeft.setLayout(panelContentLeftLayout);
		panelContentLeftLayout.setHorizontalGroup(panelContentLeftLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panelContentLeftLayout.createSequentialGroup().addContainerGap()
						.addGroup(panelContentLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(labelOutput).addComponent(labelInput))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(panelContentLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(textInput, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
								.addComponent(textOutput))
						.addContainerGap()));
		panelContentLeftLayout.setVerticalGroup(panelContentLeftLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panelContentLeftLayout.createSequentialGroup().addContainerGap()
						.addGroup(panelContentLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(labelInput).addComponent(textInput,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(panelContentLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(labelOutput).addComponent(textOutput,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		btnInput.setText("Search");
		btnInput.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnInputActionPerformed(evt);
			}
		});

		btnOuput.setText("Search");
		btnOuput.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnOuputActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout panelContentRightLayout = new javax.swing.GroupLayout(panelContentRight);
		panelContentRight.setLayout(panelContentRightLayout);
		panelContentRightLayout.setHorizontalGroup(panelContentRightLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panelContentRightLayout.createSequentialGroup().addContainerGap()
						.addGroup(panelContentRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(btnInput).addComponent(btnOuput))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		panelContentRightLayout.setVerticalGroup(panelContentRightLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panelContentRightLayout.createSequentialGroup().addContainerGap().addComponent(btnInput)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(btnOuput)
						.addContainerGap(20, Short.MAX_VALUE)));

		javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
		panelContent.setLayout(panelContentLayout);
		panelContentLayout
				.setHorizontalGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(panelContentLayout.createSequentialGroup()
								.addComponent(panelContentLeft, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(panelContentRight, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		panelContentLayout.setVerticalGroup(panelContentLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(panelContentLeft, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(panelContentRight, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
		panelMain.setLayout(panelMainLayout);
		panelMainLayout
				.setHorizontalGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(panelMainLayout.createSequentialGroup().addContainerGap()
								.addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(panelBottom, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addContainerGap()));
		panelMainLayout.setVerticalGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panelMainLayout.createSequentialGroup().addContainerGap()
						.addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(panelBottom, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(panelMain,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(panelMain,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addContainerGap()));

		pack();
	}// </editor-fold>

	// ==============================================================
	// BUTTONS
	// ==============================================================

	/**
	 * UI_Params Execute treatment button event Verify parameters before run
	 * treatment
	 * 
	 * @param evt
	 */
	private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt) {

		// Get parameters
		File fileInput = new File(textInput.getText());
		File fileOutput = new File(textOutput.getText());

		// Test parameters, is everything is clear
		if (fileInput.exists() && !fileInput.isDirectory() && fileOutput.exists() && fileOutput.isDirectory()) {

			// Load next interface
			this.dispose();
			Logs toto = new Logs();
			
			toto.addLogInformation(enumLogType.INFO, "Hello");
		}

		// If not, show warning box
		else {
			JOptionPane.showMessageDialog(this, "Bad parameters.", "Error Params", JOptionPane.ERROR_MESSAGE);
		}
	}

	/**
	 * Open a File Chooser, get the selected C file and write path on input text
	 * 
	 * @param evt
	 */
	private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {

		JFileChooser chooser = new JFileChooser();
		chooser.setCurrentDirectory(new java.io.File(""));
		chooser.setDialogTitle("Input File");
		chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
		FileFilter filter = new FileNameExtensionFilter("C File", "c");
		chooser.setFileFilter(filter);
		chooser.setAcceptAllFileFilterUsed(false);

		if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
			textInput.setText(chooser.getSelectedFile().toString());
		}

	}

	/**
	 * Open a File Chooser, get the selected folder and write path on output
	 * text
	 * 
	 * @param evt
	 */
	private void btnOuputActionPerformed(java.awt.event.ActionEvent evt) {

		JFileChooser chooser = new JFileChooser();
		chooser.setCurrentDirectory(new java.io.File(""));
		chooser.setDialogTitle("choosertitle");
		chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		chooser.setAcceptAllFileFilterUsed(false);

		if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
			textOutput.setText(chooser.getSelectedFile().toString());
		}

	}

	// ==============================================================
	// VARIABLES
	// ==============================================================

	// Variables declaration - do not modify
	private javax.swing.JButton btnExecute;
	private javax.swing.JButton btnInput;
	private javax.swing.JButton btnOuput;
	private javax.swing.JLabel labelHeader;
	private javax.swing.JLabel labelInput;
	private javax.swing.JLabel labelOutput;
	private javax.swing.JPanel panelBottom;
	private javax.swing.JPanel panelContent;
	private javax.swing.JPanel panelContentLeft;
	private javax.swing.JPanel panelContentRight;
	private javax.swing.JPanel panelHeader;
	private javax.swing.JPanel panelMain;
	private javax.swing.JTextField textInput;
	private javax.swing.JTextField textOutput;
	// End of variables declaration
}
