/* Generated By:JJTree: Do not edit this line. ASTCompoundStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCompoundStatement extends SimpleNode {
  public ASTCompoundStatement(int id) {
    super(id);
  }

  public ASTCompoundStatement(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ec5d1ce32a1aa3b98c4ec173a29c12fa (do not edit this line) */
