/* Generated By:JJTree: Do not edit this line. ASTDirectAbstractDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDirectAbstractDeclarator extends SimpleNode {
  public ASTDirectAbstractDeclarator(int id) {
    super(id);
  }

  public ASTDirectAbstractDeclarator(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=83c9c29a9d431f62b91c019307c3466c (do not edit this line) */
