/* Generated By:JJTree: Do not edit this line. ASTDeclarationList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDeclarationList extends SimpleNode {
  public ASTDeclarationList(int id) {
    super(id);
  }

  public ASTDeclarationList(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=47fc40ed20ec224e5f209e7a3620f2c7 (do not edit this line) */
