/* Generated By:JJTree: Do not edit this line. ASTExclusiveORExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExclusiveORExpression extends SimpleNode {
  public ASTExclusiveORExpression(int id) {
    super(id);
  }

  public ASTExclusiveORExpression(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=50b1b400a1750d2e715cecb95b4426a0 (do not edit this line) */
