/* Generated By:JJTree: Do not edit this line. ASTJumpStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTJumpStatement extends SimpleNode {
  public ASTJumpStatement(int id) {
    super(id);
  }

  public ASTJumpStatement(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e80d602ce3d90be1791b60e50f77b0ce (do not edit this line) */
