/* Generated By:JJTree: Do not edit this line. ASTLogicalANDExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLogicalANDExpression extends SimpleNode {
  public ASTLogicalANDExpression(int id) {
    super(id);
  }

  public ASTLogicalANDExpression(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=aa175e15089ffd30e3c5d2bc73736ce3 (do not edit this line) */
