/* Generated By:JJTree: Do not edit this line. ASTStructOrUnion.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStructOrUnion extends SimpleNode {
  public ASTStructOrUnion(int id) {
    super(id);
  }

  public ASTStructOrUnion(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3b193d95a4e9eddfbc0623d3e6f367e8 (do not edit this line) */
