/* Generated By:JJTree: Do not edit this line. ASTTypeQualifierList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTypeQualifierList extends SimpleNode {
  public ASTTypeQualifierList(int id) {
    super(id);
  }

  public ASTTypeQualifierList(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=513b380b5eb0c41357c34fb73528fe7c (do not edit this line) */
