/* Generated By:JJTree: Do not edit this line. ASTAbstractDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAbstractDeclarator extends SimpleNode {
  public ASTAbstractDeclarator(int id) {
    super(id);
  }

  public ASTAbstractDeclarator(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c26077da2e0d30bd323e46ee5f547753 (do not edit this line) */
