/* Generated By:JJTree: Do not edit this line. ASTANDExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTANDExpression extends SimpleNode {
  public ASTANDExpression(int id) {
    super(id);
  }

  public ASTANDExpression(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=46f9810993a0009b0b7b552d43bff0ab (do not edit this line) */
