/* Generated By:JJTree: Do not edit this line. ASTAssignmentExpressionInAFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAssignmentExpressionInAFunction extends SimpleNode {
  public ASTAssignmentExpressionInAFunction(int id) {
    super(id);
  }

  public ASTAssignmentExpressionInAFunction(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4fb7f83be48b83ac929380cdeb03d140 (do not edit this line) */
