/* Generated By:JJTree: Do not edit this line. ASTDeclarationInAFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDeclarationInAFunction extends SimpleNode {
  public ASTDeclarationInAFunction(int id) {
    super(id);
  }

  public ASTDeclarationInAFunction(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=21e80142b1cc6057ad06b62d8775cd70 (do not edit this line) */
