/* Generated By:JJTree: Do not edit this line. ASTDeclarationSpecifiers.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDeclarationSpecifiers extends SimpleNode {
  public ASTDeclarationSpecifiers(int id) {
    super(id);
  }

  public ASTDeclarationSpecifiers(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a5e687a7df69924f1cedf4c1a00adeac (do not edit this line) */
