/* Generated By:JJTree: Do not edit this line. ASTFunctionParameterTypeList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunctionParameterTypeList extends SimpleNode {
  public ASTFunctionParameterTypeList(int id) {
    super(id);
  }

  public ASTFunctionParameterTypeList(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=470c5a710b220dc797d70ba4d54dfa55 (do not edit this line) */
