/* Generated By:JJTree: Do not edit this line. ASTFunctionParameterDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunctionParameterDeclaration extends SimpleNode {
  public ASTFunctionParameterDeclaration(int id) {
    super(id);
  }

  public ASTFunctionParameterDeclaration(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e5ab7558339e2d3360971527b041332c (do not edit this line) */
