/* Generated By:JJTree: Do not edit this line. ASTFunctionDirectDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunctionDirectDeclarator extends SimpleNode {
  public ASTFunctionDirectDeclarator(int id) {
    super(id);
  }

  public ASTFunctionDirectDeclarator(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0200e30f256bd7cad68df3d8b70fb295 (do not edit this line) */
