/* Generated By:JJTree: Do not edit this line. ASTFunctionParameterList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunctionParameterList extends SimpleNode {
  public ASTFunctionParameterList(int id) {
    super(id);
  }

  public ASTFunctionParameterList(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=49661211f3c22df31884258b320303fd (do not edit this line) */
