/* Generated By:JJTree: Do not edit this line. ASTInitDeclaratorList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInitDeclaratorList extends SimpleNode {
  public ASTInitDeclaratorList(int id) {
    super(id);
  }

  public ASTInitDeclaratorList(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=593f68a5e4a3947ec5d73df052965d5e (do not edit this line) */
