/* Generated By:JJTree: Do not edit this line. ASTInitDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInitDeclarator extends SimpleNode {
  public ASTInitDeclarator(int id) {
    super(id);
  }

  public ASTInitDeclarator(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=537837a6d340136e7bb265ac996f2681 (do not edit this line) */
