/* Generated By:JJTree: Do not edit this line. ASTLogicalORExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLogicalORExpression extends SimpleNode {
  public ASTLogicalORExpression(int id) {
    super(id);
  }

  public ASTLogicalORExpression(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=47e0a5fe76f4e1f3496c4ae9c542f941 (do not edit this line) */
