/* Generated By:JJTree: Do not edit this line. ASTParameterDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTParameterDeclaration extends SimpleNode {
  public ASTParameterDeclaration(int id) {
    super(id);
  }

  public ASTParameterDeclaration(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b713031a6807641a7de18986288a3b45 (do not edit this line) */
