/* Generated By:JJTree: Do not edit this line. ASTPointer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPointer extends SimpleNode {
  public ASTPointer(int id) {
    super(id);
  }

  public ASTPointer(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=90664fbcb5b928015d29cfacd529e9e4 (do not edit this line) */
