/* Generated By:JJTree: Do not edit this line. ASTStatementList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatementList extends SimpleNode {
  public ASTStatementList(int id) {
    super(id);
  }

  public ASTStatementList(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8905858d7c9274d1ba91f4c225b61d51 (do not edit this line) */
