/* Generated By:JJTree: Do not edit this line. ASTStructDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStructDeclaration extends SimpleNode {
  public ASTStructDeclaration(int id) {
    super(id);
  }

  public ASTStructDeclaration(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=99735114c05c7a506cb2dab3a32c7737 (do not edit this line) */
