/* Generated By:JJTree: Do not edit this line. ASTTypeQualifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTypeQualifier extends SimpleNode {
  public ASTTypeQualifier(int id) {
    super(id);
  }

  public ASTTypeQualifier(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=feb53a6bb573a7d9ab460e7d9b774b49 (do not edit this line) */
