/* Generated By:JJTree: Do not edit this line. ASTTypeName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTypeName extends SimpleNode {
  public ASTTypeName(int id) {
    super(id);
  }

  public ASTTypeName(CParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=27a7b09ee5fd21486a8327c2911e23c1 (do not edit this line) */
